environment: staging
gcp:
  project_id: ${GCP_PROJECT_ID}
  location: ${GCP_PROJECT_LOCATION}
  staging_bucket: ${GCP_STAGING_BUCKET_STAGING}
agent:
  display_name: YOUR_AGENT_DISPLAY_NAME
  description: YOUR_AGENT_DESCRIPTION
  min_instances: 0
  max_instances: 2
  container_concurrency: 2